const { PrismaClient } = require('@prisma/client');
const PDFDocument = require('pdfkit');
const path = require('path');
const fs = require('fs');
const { shapeArabic, isArabic, ARABIC_FEATURES } = require('../utils/arabicPdf');
const prisma = new PrismaClient();

const logoPath = path.join(__dirname, '../../../frontend/public/logo.png');
// Verify logo is a valid PNG/JPG (not SVG) - PDFKit doesn't support SVG
let hasLogo = false;
try {
  if (fs.existsSync(logoPath)) {
    const buf = fs.readFileSync(logoPath, { encoding: null });
    const header = buf.slice(0, 4).toString('hex');
    // PNG: 89504e47, JPEG: ffd8ffe0/e1/e2
    hasLogo = header.startsWith('89504e47') || header.startsWith('ffd8');
  }
} catch (e) { hasLogo = false; }

// Arabic font paths
const CAIRO_REG = path.join(__dirname, '../../fonts/Cairo-Regular.ttf');
const CAIRO_BOLD = path.join(__dirname, '../../fonts/Cairo-Bold.ttf');

const NAVY = '#1a2f44';
const DARK = '#243b53';
const MID = '#486581';
const LIGHT = '#829ab1';
const BG = '#f0f4f8';
const WHITE = '#ffffff';

const formatNum = (n) => n ? n.toLocaleString('en-US') : '0';
const formatDate = (d) => d ? new Date(d).toLocaleDateString('en-GB') : '-';
const formatDateTime = (d) => {
  const x = d ? new Date(d) : new Date();
  const date = x.toLocaleDateString('en-GB');
  const time = x.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' });
  return `${date} · ${time}`;
};

// Set font based on content
const setFont = (doc, bold, text) => {
  if (isArabic(String(text || ''))) {
    doc.font(bold ? CAIRO_BOLD : CAIRO_REG);
  } else {
    doc.font(bold ? 'Helvetica-Bold' : 'Helvetica');
  }
};

// Draw a cell of text. When the run contains Arabic we pass OpenType features
// (rtla + arab) so fontkit does letter-joining and BiDi reordering — without
// them the glyphs render isolated and read as gibberish in PDF viewers.
const drawText = (doc, text, x, y, options = {}) => {
  const raw = String(text ?? '');
  const opts = isArabic(raw)
    ? { ...options, features: [...(options.features || []), ...ARABIC_FEATURES] }
    : options;
  doc.text(raw, x, y, opts);
};

// Draw a table row. Table is drawn LEFT-TO-RIGHT in the `cols` array — for RTL
// tables the caller must pass columns already in the desired visual left→right order.
const drawRow = (doc, y, cols, widths, options = {}) => {
  const { bold, bg, textColor, headerLine, fontSize } = options;
  const h = options.height || 22;
  const startX = options.startX || 30;
  const totalW = widths.reduce((a, b) => a + b, 0);

  if (bg) {
    doc.rect(startX, y, totalW, h).fill(bg);
  }

  let x = startX;
  cols.forEach((text, i) => {
    const t = String(text ?? '');
    setFont(doc, bold, t);
    const align = options.aligns?.[i] || (isArabic(t) ? 'right' : 'left');
    doc.fontSize(fontSize || 8).fillColor(textColor || DARK);
    drawText(doc, t, x + 4, y + 6, { width: widths[i] - 8, align });
    x += widths[i];
  });

  if (headerLine) {
    doc.moveTo(startX, y + h).lineTo(startX + totalW, y + h).strokeColor(NAVY).lineWidth(1.5).stroke();
  } else {
    doc.moveTo(startX, y + h).lineTo(startX + totalW, y + h).strokeColor('#d9e2ec').lineWidth(0.5).stroke();
  }

  return y + h;
};

// Shared report header: logo (right), centered title, meta line with user + date/time
const drawReportHeader = (doc, { titleAr, subtitleAr, user, pageW = 812, marginX = 30 }) => {
  let y = 25;
  const logoH = 42;

  // Logo on the right (RTL convention)
  if (hasLogo) {
    doc.image(logoPath, pageW - marginX - 50, y, { height: logoH });
  }

  // Centered title
  doc.font(CAIRO_BOLD).fontSize(20).fillColor(NAVY);
  drawText(doc, titleAr, marginX, y + 4, { align: 'center', width: pageW - marginX * 2 });

  // Subtitle under the title
  if (subtitleAr) {
    doc.font(CAIRO_REG).fontSize(11).fillColor(MID);
    drawText(doc, subtitleAr, marginX, y + 28, { align: 'center', width: pageW - marginX * 2 });
  }

  y += logoH + 12;

  // Meta line: generated by + date/time
  const genLabel = 'أنشأ التقرير:';
  const dateLabel = 'التاريخ والوقت:';
  doc.font(CAIRO_REG).fontSize(9).fillColor(LIGHT);
  // Right side: user name
  drawText(doc, `${genLabel} ${user?.name || '-'}`, marginX, y, { width: (pageW - marginX * 2) / 2, align: 'right' });
  // Left side: date/time (LTR)
  doc.font('Helvetica').fontSize(9).fillColor(LIGHT);
  doc.text(`${formatDateTime(new Date())}`, marginX, y, { width: (pageW - marginX * 2) / 2, align: 'left' });

  y += 16;
  doc.moveTo(marginX, y).lineTo(pageW - marginX, y).strokeColor(NAVY).lineWidth(1.5).stroke();
  return y + 10;
};

// ==================== PRICE QUOTE PDF ====================
const generateQuote = async (req, res) => {
  try {
    const { clientId, hotelId, items, validDays, notes, companyName, contactPerson } = req.body;

    const hotel = hotelId ? await prisma.hotel.findUnique({ where: { id: parseInt(hotelId) } }) : null;
    const client = clientId ? await prisma.client.findUnique({ where: { id: parseInt(clientId) } }) : null;

    const ref = `QT-${Date.now().toString().slice(-8)}`;
    const today = new Date();
    const validUntil = new Date(today);
    validUntil.setDate(validUntil.getDate() + (parseInt(validDays) || 30));

    const parsedItems = (items || []).map(item => ({
      description: item.description || '',
      roomType: item.roomType || '',
      nights: parseInt(item.nights) || 0,
      rooms: parseInt(item.rooms) || 0,
      rate: parseFloat(item.ratePerNight) || 0,
    }));
    parsedItems.forEach(i => { i.total = i.nights * i.rooms * i.rate; });
    const subtotal = parsedItems.reduce((s, i) => s + i.total, 0);
    const vat = Math.round(subtotal * 0.15);
    const grandTotal = subtotal + vat;

    const doc = new PDFDocument({ size: 'A4', margin: 40 });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=Quote_${ref}.pdf`);
    doc.pipe(res);

    // Register Cairo fonts
    doc.registerFont('Cairo', CAIRO_REG);
    doc.registerFont('Cairo-Bold', CAIRO_BOLD);

    // Header
    let y = 40;
    if (hasLogo) {
      doc.image(logoPath, 40, y, { height: 50 });
    }
    const headerX = hasLogo ? 110 : 40;
    const hotelName = hotel?.nameEn || hotel?.name || 'Ewaa Hotels';
    setFont(doc, true, hotelName);
    doc.fontSize(16).fillColor(NAVY).text(hotelName, headerX, y, { features: ARABIC_FEATURES });
    const loc = [hotel?.location, hotel?.city].filter(Boolean).join(', ');
    setFont(doc, false, loc);
    doc.fontSize(9).fillColor(MID).text(loc, headerX, y + 20, { features: ARABIC_FEATURES });
    y += 55;

    // Line
    doc.moveTo(40, y).lineTo(555, y).strokeColor(NAVY).lineWidth(2).stroke();
    y += 15;

    // Title
    doc.font('Helvetica-Bold').fontSize(15).fillColor(NAVY).text('PRICE QUOTATION', 40, y, { align: 'center' });
    y += 30;

    // Info columns
    doc.font('Helvetica-Bold').fontSize(10).fillColor(NAVY).text('Quotation Details', 40, y);
    doc.text('Client Details', 300, y);
    y += 16;

    const infoStyle = (label, value, x, yy) => {
      doc.font('Helvetica').fontSize(8).fillColor(MID).text(`${label}: `, x, yy, { continued: true });
      setFont(doc, false, value);
      doc.fillColor(DARK).text(value, { features: ARABIC_FEATURES });
    };

    infoStyle('Reference', ref, 40, y);
    infoStyle('Company', companyName || client?.companyName || '-', 300, y); y += 13;
    infoStyle('Date', formatDate(today), 40, y);
    infoStyle('Contact', contactPerson || client?.contactPerson || '-', 300, y); y += 13;
    infoStyle('Valid Until', formatDate(validUntil), 40, y);
    infoStyle('Phone', client?.phone || '-', 300, y); y += 13;
    const preparedBy = req.user.name;
    infoStyle('Prepared By', preparedBy, 40, y);
    infoStyle('Email', client?.email || '-', 300, y);
    y += 25;

    // Items table
    if (parsedItems.length > 0) {
      const widths = [190, 60, 60, 80, 125];
      const headers = ['Description / Room Type', 'Rooms', 'Nights', 'Rate/Night (SAR)', 'Total (SAR)'];
      y = drawRow(doc, y, headers, widths, {
        bold: true, bg: NAVY, textColor: WHITE, headerLine: true, height: 24,
        aligns: ['left', 'center', 'center', 'right', 'right']
      });

      parsedItems.forEach((item, i) => {
        const desc = item.description + (item.roomType ? ` - ${item.roomType}` : '');
        y = drawRow(doc, y, [desc, item.rooms, item.nights, formatNum(item.rate), formatNum(item.total)], widths, {
          bg: i % 2 === 0 ? BG : null,
          aligns: ['left', 'center', 'center', 'right', 'right']
        });
      });

      y += 10;
      // Totals
      const tx = 380;
      doc.font('Helvetica').fontSize(9).fillColor(MID).text('Subtotal:', tx, y);
      doc.font('Helvetica').fillColor(DARK).text(`${formatNum(subtotal)} SAR`, tx + 80, y, { align: 'right', width: 95 }); y += 15;
      doc.font('Helvetica').fillColor(MID).text('VAT (15%):', tx, y);
      doc.font('Helvetica').fillColor(DARK).text(`${formatNum(vat)} SAR`, tx + 80, y, { align: 'right', width: 95 }); y += 3;
      doc.moveTo(tx, y + 10).lineTo(555, y + 10).strokeColor(NAVY).lineWidth(1).stroke(); y += 15;
      doc.font('Helvetica-Bold').fontSize(11).fillColor(NAVY).text('Grand Total:', tx, y);
      doc.text(`${formatNum(grandTotal)} SAR`, tx + 80, y, { align: 'right', width: 95 });
      y += 30;
    }

    // Notes
    if (notes) {
      doc.font('Helvetica-Bold').fontSize(10).fillColor(NAVY).text('Notes & Terms:', 40, y); y += 14;
      setFont(doc, false, notes);
      doc.fontSize(8).fillColor(MID).text(notes, 40, y, { width: 515, features: ARABIC_FEATURES });
      y += doc.heightOfString(notes, { width: 515 }) + 15;
    }

    // Standard terms
    doc.font('Helvetica-Bold').fontSize(9).fillColor(NAVY).text('Terms & Conditions:', 40, y); y += 13;
    const terms = [
      'Prices are in Saudi Riyals (SAR) and include applicable taxes unless stated otherwise.',
      'This quotation is valid for the period mentioned above.',
      'Rates are subject to availability at the time of booking confirmation.',
    ];
    terms.forEach(t => {
      doc.font('Helvetica').fontSize(7).fillColor(LIGHT).text(`•  ${t}`, 40, y, { width: 515 }); y += 11;
    });

    doc.end();
  } catch (err) {
    console.error('Quote PDF error:', err);
    res.status(500).json({ message: err.message });
  }
};

// ==================== CLIENT REPORT PDF ====================
const generateClientReport = async (req, res) => {
  try {
    const { type, hotelId, salesRepId } = req.query;
    const where = {};
    if (type) where.clientType = type;
    if (hotelId) where.hotelId = parseInt(hotelId);

    const ADMIN_ROLES = ['admin', 'general_manager', 'vice_gm'];
    if (!ADMIN_ROLES.includes(req.user.role) && req.user.role !== 'contract_officer') {
      if (req.user.role === 'assistant_sales' && req.user.managerId) {
        const subs = await prisma.user.findMany({ where: { managerId: req.user.managerId }, select: { id: true } });
        where.salesRepId = { in: [req.user.managerId, ...subs.map(s => s.id)] };
      } else if (req.user.role === 'sales_director') {
        const subs = await prisma.user.findMany({ where: { managerId: req.user.id }, select: { id: true } });
        where.salesRepId = { in: [req.user.id, ...subs.map(s => s.id)] };
      } else {
        where.salesRepId = req.user.id;
      }
    }

    // Explicit rep filter from UI (admins or overriding the scoped default)
    if (salesRepId) where.salesRepId = parseInt(salesRepId);

    const clients = await prisma.client.findMany({
      where,
      include: {
        salesRep: { select: { name: true } },
        hotel: { select: { name: true } },
        _count: { select: { contracts: true, visits: true } },
      },
      orderBy: { companyName: 'asc' },
    });

    const doc = new PDFDocument({ size: 'A4', layout: 'landscape', margin: 30 });
    doc.registerFont('Cairo', CAIRO_REG);
    doc.registerFont('Cairo-Bold', CAIRO_BOLD);
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=Client_Report.pdf`);
    doc.pipe(res);

    const pageW = 812; // landscape A4 width
    let y = drawReportHeader(doc, {
      titleAr: 'تقرير العملاء',
      subtitleAr: `فنادق إيواء — إجمالي ${clients.length} عميل`,
      user: req.user,
      pageW,
    });

    // Table columns are drawn left→right on the page. For an RTL table we
    // arrange them so the first (Arabic-reader) column "#" sits on the right.
    // visual order (from RIGHT to LEFT for reader): # | الشركة | جهة الاتصال | الهاتف | النوع | الفندق | المندوب | العقود | الزيارات
    // on-page order (LEFT to RIGHT): الزيارات | العقود | المندوب | الفندق | النوع | الهاتف | جهة الاتصال | الشركة | #
    const widths = [55, 55, 110, 115, 60, 90, 115, 170, 30];
    const headers = ['الزيارات', 'العقود', 'المندوب', 'الفندق', 'النوع', 'الهاتف', 'جهة الاتصال', 'الشركة', '#'];
    const aligns = ['center', 'center', 'right', 'right', 'center', 'center', 'right', 'right', 'center'];

    y = drawRow(doc, y, headers, widths, {
      bold: true, bg: NAVY, textColor: WHITE, headerLine: true, height: 24, aligns, fontSize: 9,
    });

    const typeLabel = { active: 'نشط', lead: 'محتمل', inactive: 'غير نشط' };

    clients.forEach((c, i) => {
      if (y > 530) {
        doc.addPage();
        y = drawReportHeader(doc, {
          titleAr: 'تقرير العملاء',
          subtitleAr: `فنادق إيواء — إجمالي ${clients.length} عميل`,
          user: req.user,
          pageW,
        });
        y = drawRow(doc, y, headers, widths, {
          bold: true, bg: NAVY, textColor: WHITE, headerLine: true, height: 24, aligns, fontSize: 9,
        });
      }
      y = drawRow(doc, y, [
        c._count.visits, c._count.contracts, c.salesRep?.name || '-', c.hotel?.name || '-',
        typeLabel[c.clientType] || c.clientType, c.phone || '-',
        c.contactPerson || '-', c.companyName, i + 1
      ], widths, {
        bg: i % 2 === 0 ? BG : null, aligns,
      });
    });

    // Summary
    y += 15;
    const active = clients.filter(c => c.clientType === 'active').length;
    const leads = clients.filter(c => c.clientType === 'lead').length;
    const inactive = clients.filter(c => c.clientType === 'inactive').length;

    doc.font(CAIRO_BOLD).fontSize(9).fillColor(NAVY);
    const summary = `نشط: ${active}   |   محتمل: ${leads}   |   غير نشط: ${inactive}`;
    drawText(doc, summary, 30, y, { align: 'center', width: pageW - 60 });

    doc.end();
  } catch (err) {
    console.error('Client report PDF error:', err);
    res.status(500).json({ message: err.message });
  }
};

module.exports = { generateQuote, generateClientReport };
